# Generated by Django 4.1.2 on 2022-12-08 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(choices=[('fruta', 'fruta'), ('verdura', 'verdura')], max_length=100)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_de_vto', models.DateField()),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('codigo', models.IntegerField(blank=True, null=True, verbose_name='Nº codigo')),
                ('productor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Razon social del productor')),
                ('entregado', models.BooleanField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
