# Generated by Django 4.1.2 on 2022-12-11 00:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfarm', '0002_alter_entregable_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('contenido', ckeditor.fields.RichTextField(verbose_name='Contenido')),
            ],
        ),
    ]
