# Generated by Django 4.1.2 on 2022-12-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfarm', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='imagen',
            field=models.ImageField(blank=True, default='avatar.png', upload_to='avatares'),
        ),
    ]
