# Generated by Django 4.1.2 on 2022-12-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfarm', '0005_alter_entregable_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='imagen',
            field=models.ImageField(blank=True, default='avatares/avatar.jpg', upload_to='avatares'),
        ),
    ]
