# Generated by Django 4.1.2 on 2022-12-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfarm', '0007_alter_entregable_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='path',
            field=models.CharField(default='', max_length=200, verbose_name='Path'),
            preserve_default=False,
        ),
    ]
