# Generated by Django 4.1.2 on 2022-12-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfarm', '0008_post_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='codigo',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Nº codigo'),
        ),
    ]
